CREATE TABLE [dbo].[Audit]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[Table] NVARCHAR(200) NOT NULL,
	[Column] NVARCHAR(200) NULL,
	[Action] NVARCHAR(20) NOT NULL,
	[UserId] INT NOT NULL,
	[Key] INT NOT NULL,
	[OldValue] NVARCHAR(MAX),
	[NewValue] NVARCHAR(MAX),
	[Time] DATETIME NOT NULL DEFAULT(GETUTCDATE()),
	FOREIGN KEY (UserId) REFERENCES [User](Id)
)