CREATE TABLE [dbo].[Autoclave]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[RoomId] INT NOT NULL,
	[Name] NVARCHAR(100) NOT NULL,
	[Details] NVARCHAR(MAX) NULL,
	[IsDeleted] BIT DEFAULT(0),
	FOREIGN KEY (RoomId) REFERENCES Room(Id)
)
