CREATE TABLE [dbo].[Recipe]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[Name] NVARCHAR(MAX) NOT NULL,
	[Type] TINYINT NOT NULL,
	[Text] NVARCHAR(MAX) NOT NULL,
	[UnitsCreated] INT NOT NULL,
	[IsDeleted] BIT NOT NULL DEFAULT(0)
)
